### PR TITLE
chore(build): switch to yarn workspaces and simplify dotfiles and config

### PR DESCRIPTION
**Pull request by jquense**
Feel free to ignore if this much repo reorg is too presumptuous. I wanted to send over a few PR's but the current state of the repo was a bit hard work in since it hadn't been updated in a while (love how quickly js code gets out of date!)

Some of this is a lint update and then just some reorg to consolidate and eliminate extra dotfiles and repeated ts config.

### CODE REVIEW

**Comment by jquense** [comment]
>  but maybe you know of some advantages I am not aware of?

yeah there are a few advantages, the installation in general is much faster, and you only end up with a single lock file for the entire project. You can also make broader use of `yarn upgrade` across the whole project. Overall tho, b/c yarn _is_ the installation tool it generally does a better job at flattening, hoisting, etc than lerna can as well as being significantly less error prone. Not to mention that a contributor doesn't need to learn a new tool to get setup, they just run `yarn` like normal. In fact you really only need to use lerna for publishing.

The lifecycle thing is a bit annoying but easily worked around via a `lerna run prepublishOnly`  on `postinstall` at the root. we've got a bunch of monorepos around and workspaces have been a win overall.

**Comment by renke** [comment]
Do you have any exemplary monorepo repostories I could learn from?

**Comment by jquense** [comment]
sure:

https://github.com/4Catalyzer/javascript
https://github.com/jquense/react-widgets

**Comment by renke** [comment]
Hi @jquense 

you said:

> You can also make broader use of yarn upgrade across the whole project.

I couldn't find any info on how to do this? – Let's say I want to upgrade TypeScript to the latest version in all packages. How can I do this (other than `lerna run – yarn upgrade …`)?

**Comment by jquense** [comment]
You can yarn upgrade from the root, I usually use `yarn upgrade-interactive --latest` so I can pick and choose

**Pull request merged**
